use_frameworks!

platform :ios, '10.0'

target 'VMOS_Example' do
  pod 'VMOS', :path => '../'

  target 'VMOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
